from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class NewsAgentOutput(BaseModel):
    sentiment: Literal["bullish", "bearish", "neutral"] = "neutral"
    summary: str = ""
    key_themes: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class FinancialMetricsAgentOutput(BaseModel):
    valuation_rating: Literal["overvalued", "fairly valued", "undervalued"] = "fairly valued"
    analysis_summary: str = ""
    key_metrics: Dict[str, Any] = Field(default_factory=dict)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class SECFilingAgentOutput(BaseModel):
    filing_summary: str = ""
    risk_signals: List[str] = Field(default_factory=list)
    latest_filing_type: str = ""
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class RiskAgentOutput(BaseModel):
    risk_level: Literal["LOW", "MEDIUM", "HIGH"] = "MEDIUM"
    risk_factors: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class EarningsAgentOutput(BaseModel):
    earnings_summary: str = ""
    tone: Literal["positive", "mixed", "negative", "unknown"] = "unknown"
    key_points: List[str] = Field(default_factory=list)
    next_catalyst: str = ""
    sources: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class IrPage(BaseModel):
    url: str = ""
    title: str = ""
    provider: str = ""
    text_excerpt: str = ""
    char_count: int = 0


class IrMaterialsOutput(BaseModel):
    ticker: str = ""
    enabled: bool = True
    provider: str = ""
    sources: List[str] = Field(default_factory=list)
    pages: List[IrPage] = Field(default_factory=list)
    excerpt: str = ""
    error: str = ""


class MacroAgentOutput(BaseModel):
    macro_summary: str = ""
    relevance: Literal["high", "medium", "low", "none"] = "medium"
    themes: List[str] = Field(default_factory=list)
    portfolio_implications: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class VerificationAgentOutput(BaseModel):
    verified_claims: List[str] = Field(default_factory=list)
    unsupported_claims: List[str] = Field(default_factory=list)
    coverage_notes: List[str] = Field(default_factory=list)
    groundedness_score: float = Field(default=0.5, ge=0.0, le=1.0)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class DebateAgentOutput(BaseModel):
    stance: Literal["bull", "bear"] = "bull"
    thesis: str = ""
    key_points: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    error_message: str = ""


class DebateOutput(BaseModel):
    bull: DebateAgentOutput
    bear: DebateAgentOutput


class ReportSection(BaseModel):
    title: str
    content: str


class FinalReportOutput(BaseModel):
    ticker: str
    report_title: str = ""
    executive_summary: str = ""
    sections: List[ReportSection] = Field(default_factory=list)
    recommendation: str = ""
    disclaimer: str = (
        "This report is generated by AI for educational purposes only "
        "and is not financial advice."
    )
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class InvestmentMemoOutput(BaseModel):
    """Phase 12 — short shareable investment decision memo."""

    ticker: str
    memo_title: str = ""
    one_liner: str = ""
    investment_thesis: str = ""
    key_numbers: List[str] = Field(default_factory=list)
    catalysts: List[str] = Field(default_factory=list)
    risks: List[str] = Field(default_factory=list)
    bull_case_summary: str = ""
    bear_case_summary: str = ""
    decision: Literal["BUY", "HOLD", "SELL", "WATCH"] = "HOLD"
    conviction: Literal["low", "medium", "high"] = "medium"
    time_horizon: str = "3-12 months"
    what_would_change_my_mind: List[str] = Field(default_factory=list)
    disclaimer: str = (
        "This investment memo is generated by AI for educational purposes only "
        "and is not financial advice."
    )
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class FactItem(BaseModel):
    content: str
    source: str


class InsightItem(BaseModel):
    content: str
    generated_by: str


class FactsAndInsights(BaseModel):
    facts: List[FactItem] = Field(default_factory=list)
    insights: List[InsightItem] = Field(default_factory=list)


class PerAgentConfidence(BaseModel):
    news: float = 0.0
    financial: float = 0.0
    sec: float = 0.0
    earnings: float = 0.0
    macro: float = 0.0
    risk: float = 0.0
    bull: float = 0.0
    bear: float = 0.0
    verification: float = 0.0
    report: float = 0.0
    memo: float = 0.0


class AnalysisResponse(BaseModel):
    ticker: str
    final_report: FinalReportOutput
    investment_memo: Optional[InvestmentMemoOutput] = None
    news_output: Optional[NewsAgentOutput] = None
    metrics_output: Optional[FinancialMetricsAgentOutput] = None
    sec_output: Optional[SECFilingAgentOutput] = None
    earnings_output: Optional[EarningsAgentOutput] = None
    ir_materials: Optional[IrMaterialsOutput] = None
    macro_output: Optional[MacroAgentOutput] = None
    risk_output: Optional[RiskAgentOutput] = None
    verification_output: Optional[VerificationAgentOutput] = None
    run_id: str = ""
    overall_confidence_score: float = Field(default=0.0, ge=0.0, le=1.0)
    per_agent_confidence: PerAgentConfidence = Field(default_factory=PerAgentConfidence)
    validation_warnings: List[str] = Field(default_factory=list)
    facts_and_insights: FactsAndInsights = Field(default_factory=FactsAndInsights)
    debate_output: Optional[DebateOutput] = None


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"] = "user"
    content: str


class ChatRequest(BaseModel):
    question: str
    analysis_context: Optional[Dict[str, Any]] = None


class ChatResponse(BaseModel):
    ticker: str
    answer: str
    sources_used: List[str] = Field(default_factory=list)


class PortfolioHolding(BaseModel):
    ticker: str
    current_price: Optional[float] = None
    pe_ratio: Optional[float] = None
    risk_level: str = "UNKNOWN"
    valuation: str = "unknown"
    weight_pct: float = 0.0
    shares: Optional[float] = None
    avg_cost: Optional[float] = None
    market_value: Optional[float] = None
    unrealized_gain_pct: Optional[float] = None


class PortfolioAnalysis(BaseModel):
    holdings: List[PortfolioHolding] = Field(default_factory=list)
    avg_pe: Optional[float] = None
    risk_mix: Dict[str, int] = Field(default_factory=dict)
    sector_note: str = ""
    weakest_ticker: Optional[str] = None
    summary: str = ""
    total_market_value: Optional[float] = None
    weighted_by_real_positions: bool = False
    disclaimer: str = (
        "Portfolio view is illustrative, not investment advice. "
        "Based on latest cached or live quotes."
    )


class PortfolioBriefingOutput(BaseModel):
    headline: str = ""
    summary: str = ""
    highlights: List[str] = Field(default_factory=list)
    risks: List[str] = Field(default_factory=list)
    watch_tickers: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    error_message: str = ""


class DailyBriefingResponse(BaseModel):
    id: int
    generated_at: str
    headline: str
    summary: str
    highlights: List[str] = Field(default_factory=list)
    risks: List[str] = Field(default_factory=list)
    watch_tickers: List[str] = Field(default_factory=list)
    holdings_snapshot: List[PortfolioHolding] = Field(default_factory=list)
    confidence_score: float = 0.5
    status: str = "ok"
    error_message: str = ""
    disclaimer: str = (
        "Daily briefing is AI-generated research tooling, not investment advice."
    )
