from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class NewsAgentOutput(BaseModel):
    sentiment: Literal["bullish", "bearish", "neutral"] = "neutral"
    summary: str = ""
    key_themes: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class FinancialMetricsAgentOutput(BaseModel):
    valuation_rating: Literal["overvalued", "fairly valued", "undervalued"] = "fairly valued"
    analysis_summary: str = ""
    key_metrics: Dict[str, Any] = Field(default_factory=dict)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class SECFilingAgentOutput(BaseModel):
    filing_summary: str = ""
    risk_signals: List[str] = Field(default_factory=list)
    latest_filing_type: str = ""
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class RiskAgentOutput(BaseModel):
    risk_level: Literal["LOW", "MEDIUM", "HIGH"] = "MEDIUM"
    risk_factors: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class DebateAgentOutput(BaseModel):
    stance: Literal["bull", "bear"] = "bull"
    thesis: str = ""
    key_points: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    error_message: str = ""


class DebateOutput(BaseModel):
    bull: DebateAgentOutput
    bear: DebateAgentOutput


class ReportSection(BaseModel):
    title: str
    content: str


class FinalReportOutput(BaseModel):
    ticker: str
    report_title: str = ""
    executive_summary: str = ""
    sections: List[ReportSection] = Field(default_factory=list)
    recommendation: str = ""
    disclaimer: str = (
        "This report is generated by AI for educational purposes only "
        "and is not financial advice."
    )
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    validation_warning: str = ""
    error_message: str = ""


class FactItem(BaseModel):
    content: str
    source: str


class InsightItem(BaseModel):
    content: str
    generated_by: str


class FactsAndInsights(BaseModel):
    facts: List[FactItem] = Field(default_factory=list)
    insights: List[InsightItem] = Field(default_factory=list)


class PerAgentConfidence(BaseModel):
    news: float = 0.0
    financial: float = 0.0
    sec: float = 0.0
    risk: float = 0.0
    bull: float = 0.0
    bear: float = 0.0
    report: float = 0.0


class AnalysisResponse(BaseModel):
    ticker: str
    final_report: FinalReportOutput
    news_output: Optional[NewsAgentOutput] = None
    metrics_output: Optional[FinancialMetricsAgentOutput] = None
    sec_output: Optional[SECFilingAgentOutput] = None
    risk_output: Optional[RiskAgentOutput] = None
    run_id: str = ""
    overall_confidence_score: float = Field(default=0.0, ge=0.0, le=1.0)
    per_agent_confidence: PerAgentConfidence = Field(default_factory=PerAgentConfidence)
    validation_warnings: List[str] = Field(default_factory=list)
    facts_and_insights: FactsAndInsights = Field(default_factory=FactsAndInsights)
    debate_output: Optional[DebateOutput] = None


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"] = "user"
    content: str


class ChatRequest(BaseModel):
    question: str
    analysis_context: Optional[Dict[str, Any]] = None


class ChatResponse(BaseModel):
    ticker: str
    answer: str
    sources_used: List[str] = Field(default_factory=list)


class PortfolioHolding(BaseModel):
    ticker: str
    current_price: Optional[float] = None
    pe_ratio: Optional[float] = None
    risk_level: str = "UNKNOWN"
    valuation: str = "unknown"
    weight_pct: float = 0.0


class PortfolioAnalysis(BaseModel):
    holdings: List[PortfolioHolding] = Field(default_factory=list)
    avg_pe: Optional[float] = None
    risk_mix: Dict[str, int] = Field(default_factory=dict)
    sector_note: str = ""
    weakest_ticker: Optional[str] = None
    summary: str = ""
    disclaimer: str = (
        "Portfolio view is illustrative — not investment advice. "
        "Based on latest cached or live quotes."
    )
