"""Investment Memo Agent (Phase 12) — turns the full research pipeline into a
short, shareable decision memo (thesis, numbers, risks, conviction).
"""

import json
import logging
import traceback
from typing import Any, Dict, Optional

from app.agents.llm import call_openai_json
from app.models.agent_schemas import InvestmentMemoOutput
from app.observability.logger import get_logger, log_event

logger = get_logger("investment_memo_agent")

_DISCLAIMER = (
    "This investment memo is generated by AI for educational purposes only "
    "and is not financial advice. Do your own research before investing."
)


def _fallback(
    ticker: str,
    final_report: Dict[str, Any],
    risk_output: Optional[Dict[str, Any]] = None,
    debate_output: Optional[Dict[str, Any]] = None,
    metrics_output: Optional[Dict[str, Any]] = None,
) -> InvestmentMemoOutput:
    risk_output = risk_output or {}
    debate_output = debate_output or {}
    metrics_output = metrics_output or {}
    bull = debate_output.get("bull") or {}
    bear = debate_output.get("bear") or {}
    metrics = metrics_output.get("key_metrics") or {}

    key_numbers = []
    for label, key in (
        ("Price", "current_price"),
        ("P/E", "pe_ratio"),
        ("Market cap", "market_cap"),
        ("EPS", "eps"),
    ):
        val = metrics.get(key)
        if val is not None:
            key_numbers.append(f"{label}: {val}")

    rec = (final_report.get("recommendation") or "HOLD").upper()
    decision = "HOLD"
    if "BUY" in rec:
        decision = "BUY"
    elif "SELL" in rec:
        decision = "SELL"
    elif "WATCH" in rec:
        decision = "WATCH"

    return InvestmentMemoOutput(
        ticker=ticker,
        memo_title=f"{ticker} Investment Memo",
        one_liner=(
            final_report.get("executive_summary") or f"Automated memo for {ticker}."
        )[:280],
        investment_thesis=(
            final_report.get("executive_summary")
            or f"Multi-agent research snapshot for {ticker}."
        ),
        key_numbers=key_numbers or ["Limited quantitative inputs available."],
        catalysts=["See report catalysts / earnings section."],
        risks=list(risk_output.get("risk_factors") or ["Risk assessment incomplete."])[:5],
        bull_case_summary=bull.get("thesis") or "Bull case not available.",
        bear_case_summary=bear.get("thesis") or "Bear case not available.",
        decision=decision,  # type: ignore[arg-type]
        conviction="medium",
        time_horizon="3-12 months",
        what_would_change_my_mind=[
            "Material change in fundamentals or filings.",
            "Clear shift in risk/reward vs current price.",
        ],
        disclaimer=_DISCLAIMER,
        confidence_score=0.45,
    )


async def generate_investment_memo(
    ticker: str,
    final_report: Dict[str, Any],
    stock_data: Optional[Dict[str, Any]] = None,
    metrics_output: Optional[Dict[str, Any]] = None,
    risk_output: Optional[Dict[str, Any]] = None,
    debate_output: Optional[Dict[str, Any]] = None,
    earnings_output: Optional[Dict[str, Any]] = None,
    macro_output: Optional[Dict[str, Any]] = None,
    verification_output: Optional[Dict[str, Any]] = None,
) -> InvestmentMemoOutput:
    """Synthesize a concise investment memo from the completed research graph."""
    fallback = _fallback(
        ticker,
        final_report or {},
        risk_output=risk_output,
        debate_output=debate_output,
        metrics_output=metrics_output,
    )
    try:
        payload = json.dumps(
            {
                "ticker": ticker,
                "stock_data": stock_data or {},
                "final_report": final_report or {},
                "metrics_output": metrics_output or {},
                "risk_output": risk_output or {},
                "debate_output": debate_output or {},
                "earnings_output": earnings_output or {},
                "macro_output": macro_output or {},
                "verification_output": verification_output or {},
            },
            default=str,
        )
        result = await call_openai_json(
            system_prompt=(
                "You are QuantPilot's Investment Memo Agent. Turn multi-agent stock "
                "research into a short, shareable investment memo a portfolio manager "
                "could skim in under a minute. Be concrete; do not invent numbers that "
                "are not in the inputs. decision must be one of BUY, HOLD, SELL, WATCH. "
                "conviction must be one of low, medium, high. Respond ONLY with JSON: "
                '{"memo_title": string, "one_liner": string (<=280 chars), '
                '"investment_thesis": string, "key_numbers": [string], '
                '"catalysts": [string], "risks": [string], '
                '"bull_case_summary": string, "bear_case_summary": string, '
                '"decision": "BUY"|"HOLD"|"SELL"|"WATCH", '
                '"conviction": "low"|"medium"|"high", '
                '"time_horizon": string, "what_would_change_my_mind": [string], '
                '"disclaimer": string, "confidence_score": number 0-1}'
            ),
            user_prompt=(
                f"Write an investment memo for {ticker} from this research payload:\n\n"
                f"{payload[:14000]}"
            ),
            fallback=fallback.model_dump(),
        )
        merged = {**result, "ticker": ticker}
        if not merged.get("disclaimer"):
            merged["disclaimer"] = _DISCLAIMER
        return InvestmentMemoOutput.model_validate(merged)
    except Exception as exc:
        log_event(
            logger,
            logging.ERROR,
            "Investment memo generation failed",
            ticker=ticker,
            error=str(exc),
            traceback=traceback.format_exc(),
        )
        fb = fallback.model_dump()
        fb["confidence_score"] = 0.0
        fb["error_message"] = str(exc)
        return InvestmentMemoOutput.model_validate(fb)
